### PR TITLE
Refine Chinese translation

### PR DESCRIPTION
**Pull request by pengchzn**

### CODE REVIEW

**Comment by vpj** [comment]
Ready for merge?

**Comment by pengchzn** [comment]
Yes, I have completed the translation of multi-head attention and some small files (translating with Unicode is somewhat unintuitive).

**Comment by pengchzn** [comment]
Yes, I have completed the translation of multi-head attention and some small files (translating with Unicode is somewhat unintuitive).

**Comment by pengchzn** [comment]
Other than a few minor formatting issues, I don't see any other problems. I will correct them in the next PR.

You can mention it, as someone willing to help could reach out to me, thanks!

**Pull request merged**
