### PR TITLE
GATv2 refactoring

### PR DESCRIPTION
**Pull request by shakedbr**
Hi @vpj 
* Fixed readme
* Added some clarification about this GATv2 implementation
* Updated the dropout in the Core experiment, and added updated links to the experiment.
* The paper author's tweeter IDs are `@shakedbr @urialon1 @yahave`

Can you generate the docs (and the experiment comparison)?

Thanks!

Shaked

### CODE REVIEW

**Comment by vpj** [comment]
I will read the paper and retweet, by Saturday

Thanks

**Comment by vpj** [comment]
I cleaned up the experiment code to reuse the GAT experiment.

https://nn.labml.ai/graphs/gatv2/experiment.html

**Comment by vpj** [comment]
Added a little more details to the intro. Let me know if it's ok https://nn.labml.ai/graphs/gatv2/index.html

**Comment by shakedbr** [comment]
Looks great!

**Pull request merged**
