### PR TITLE
Refine Chinese translation

### PR DESCRIPTION
**Pull request by pengchzn**
I have refined the translation of [translate_cache/__init__.zh.json](https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/translate_cache/__init__.zh.json) as a test. 

Also, I found that the chapter on `Sophia-G Optimizer` seems to be missing in the Chinese and Japanese versions.

### CODE REVIEW

**Comment by vpj** [comment]
Created the translated pages for Sophia-G and some other missing files. Couldn't get automatic translations because we have not paid for that subscription. 😔

I had to resolve some line during the merge, because the cache was outdated; sorry I should have done this before you started refining translation. Please check if it's ok.

Thanks

**Comment by pengchzn** [comment]
Ok, thanks! I will be responsible for the manual translation of Chinese.

**Comment by vpj** [comment]
Which one are you planning to do next?

**Comment by pengchzn** [comment]
I will translate according to the order of the [homepage](https://nn.labml.ai/), the next one is Transformers

**Pull request merged**
